/*
 * Graph Communities for Obsidian
 * Generated from src/graph-core.js and src/plugin.js.
 * Do not edit this file directly; run: node scripts/build.mjs
 */
'use strict';

const GraphCommunitiesCore = (() => {
  const module = { exports: {} };
  const exports = module.exports;
  'use strict';

  const DEFAULT_PALETTE = [
    '#5AA9FF',
    '#FF7A7A',
    '#6FE39A',
    '#C58CFF',
    '#FFC857',
    '#46D7D0',
    '#FF86C8',
    '#A8D65E',
    '#FF9F43',
    '#738CFF',
    '#E3A6FF',
    '#6FD0FF',
  ];

  const GENERIC_DOCUMENT_NAMES = new Set([
    'readme', 'index', 'home', 'homepage', 'overview', 'summary', 'contents',
    'toc', 'moc', 'dashboard', 'start', 'welcome', 'docs', 'documentation',
    'resources', 'changelog', 'license', 'contributing', 'sitemap', 'agents',
    'skills', 'library', 'internal', 'site', 'sources', 'source', 'src',
    'references', 'reference', 'examples', 'example', 'tests', 'test', 'github',
    'workflows', 'workflow', 'markdown', 'lectures', 'archive', 'legacy',
    'skill output samples', 'release plans', 'issues archive', 'content',
    '首页', '主页', '目录', '索引', '导航', '总览', '概览', '说明', '欢迎',
  ]);

  const GENERIC_TERMS = new Set([
    ...GENERIC_DOCUMENT_NAMES,
    'note', 'notes', 'file', 'files', 'document', 'documents', '项目', '文档',
    '笔记', '内容', '相关', '记录', '工作', '资料', '文件', '知识库',
  ]);

  function createGraph(nodeIds = []) {
    const graph = new Map();
    for (const id of nodeIds) ensureNode(graph, id);
    return graph;
  }

  function ensureNode(graph, id) {
    const key = String(id);
    if (!graph.has(key)) graph.set(key, new Map());
    return graph.get(key);
  }

  function addUndirectedEdge(graph, source, target, weight = 1) {
    const a = String(source);
    const b = String(target);
    const w = Number(weight);
    ensureNode(graph, a);
    ensureNode(graph, b);
    if (a === b || !Number.isFinite(w) || w <= 0) return;
    graph.get(a).set(b, (graph.get(a).get(b) || 0) + w);
    graph.get(b).set(a, (graph.get(b).get(a) || 0) + w);
  }

  function buildWeightedGraph(edges = [], nodeIds = []) {
    const graph = createGraph(nodeIds);
    for (const edge of edges) {
      if (Array.isArray(edge)) {
        addUndirectedEdge(graph, edge[0], edge[1], edge[2] == null ? 1 : edge[2]);
      } else if (edge && edge.source != null && edge.target != null) {
        addUndirectedEdge(graph, edge.source, edge.target, edge.weight == null ? 1 : edge.weight);
      }
    }
    return graph;
  }

  function graphFromResolvedLinks(resolvedLinks = {}, nodeIds = []) {
    const graph = createGraph(nodeIds);
    for (const [source, targets] of Object.entries(resolvedLinks || {})) {
      ensureNode(graph, source);
      for (const [target, count] of Object.entries(targets || {})) {
        addUndirectedEdge(graph, source, target, Math.max(1, Number(count) || 1));
      }
    }
    return graph;
  }

  function cloneGraph(graph, weightTransform = (_source, _target, weight) => weight) {
    const cloned = createGraph(graph.keys());
    const seen = new Set();
    for (const [source, neighbors] of graph.entries()) {
      for (const [target, weight] of neighbors.entries()) {
        const key = source < target ? `${source}\u0000${target}` : `${target}\u0000${source}`;
        if (seen.has(key)) continue;
        seen.add(key);
        addUndirectedEdge(cloned, source, target, weightTransform(source, target, weight));
      }
    }
    return cloned;
  }

  function humanizeSegment(value) {
    return String(value || '')
      .replace(/\.md$/i, '')
      .replace(/^\d{1,3}(?:[._-]|\s)+/u, '')
      .replace(/[_-]+/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function normalizedTerm(value) {
    return humanizeSegment(value).normalize('NFKC').toLocaleLowerCase().trim();
  }

  function basenameWithoutExtension(id) {
    const parts = String(id || '').split('/');
    return (parts.pop() || '').replace(/\.md$/i, '');
  }

  function isGenericLabel(value) {
    const normalized = normalizedTerm(value).replace(/\s+/g, '');
    if (!normalized) return true;
    if (GENERIC_DOCUMENT_NAMES.has(normalized)) return true;
    return /(?:readme|index|homepage|dashboard|overview|contents|目录|索引|导航|首页|总览|概览)/iu.test(normalized);
  }

  function isNavigationDocument(id, document = {}) {
    if (document.navigation != null) return Boolean(document.navigation);
    const values = [basenameWithoutExtension(id), document.title, ...(document.aliases || [])];
    return values.filter(Boolean).some((value) => isGenericLabel(value));
  }

  function tokenizeSemanticText(value) {
    const normalized = String(value || '').normalize('NFKC').toLocaleLowerCase();
    const terms = new Set();
    for (const match of normalized.matchAll(/[a-z][a-z0-9+#.]{1,}/giu)) {
      const term = match[0].replace(/^[._-]+|[._-]+$/g, '');
      if (term.length >= 2 && !GENERIC_TERMS.has(term)) terms.add(term);
    }
    for (const match of normalized.matchAll(/[\p{Script=Han}]{2,}/gu)) {
      const chunk = match[0];
      if (chunk.length <= 10 && !GENERIC_TERMS.has(chunk)) terms.add(chunk);
      const maximum = Math.min(4, chunk.length);
      for (let size = 2; size <= maximum; size += 1) {
        for (let index = 0; index <= chunk.length - size && index < 18; index += 1) {
          const term = chunk.slice(index, index + size);
          if (!GENERIC_TERMS.has(term)) terms.add(term);
        }
      }
    }
    return [...terms];
  }

  function addFeature(target, term, weight) {
    const key = normalizedTerm(term);
    if (!key || GENERIC_TERMS.has(key)) return;
    target.set(key, Math.max(target.get(key) || 0, weight));
  }

  function addTextFeatures(target, value, weight) {
    for (const term of tokenizeSemanticText(value)) addFeature(target, term, weight);
  }

  function parsePriorityKeywords(value) {
    const entries = Array.isArray(value)
      ? value
      : String(value || '').split(/[,，;；\n]+/u);
    return [...new Set(entries.map((entry) => normalizedTerm(entry)).filter(Boolean))];
  }

  function normalizeDocumentInput(input, graph) {
    const source = input instanceof Map
      ? [...input.entries()].map(([id, value]) => ({ id, ...(value || {}) }))
      : Array.isArray(input) ? input : [];
    const byId = new Map(source.map((document) => [String(document.id || document.path), document]));
    const documents = new Map();
    for (const id of graph.keys()) {
      const raw = byId.get(id) || {};
      const path = String(raw.path || id);
      documents.set(id, {
        id,
        path,
        title: String(raw.title || basenameWithoutExtension(path)),
        aliases: asStringArray(raw.aliases),
        tags: asStringArray(raw.tags).map((tag) => tag.replace(/^#/, '')),
        headings: asStringArray(raw.headings).slice(0, 16),
        navigation: raw.navigation,
      });
    }
    return documents;
  }

  function asStringArray(value) {
    if (Array.isArray(value)) return value.flatMap(asStringArray).filter(Boolean);
    if (value == null) return [];
    return String(value).split(/[,，]/u).map((entry) => entry.trim()).filter(Boolean);
  }

  function deriveProjectAssignments(documents, options = {}) {
    const maximumSize = clamp(Math.round(numericOption(options, 'projectMaxSize', 1200)), 10, 4000);
    const counts = new Map();
    for (const document of documents.values()) {
      const directories = document.path.split('/').slice(0, -1);
      for (let depth = 1; depth <= directories.length; depth += 1) {
        const prefix = directories.slice(0, depth).join('/');
        counts.set(prefix, (counts.get(prefix) || 0) + 1);
      }
    }

    const projects = new Map();
    for (const document of documents.values()) {
      const directories = document.path.split('/').slice(0, -1);
      const prefixes = directories.map((_, index) => directories.slice(0, index + 1).join('/'));
      if (!prefixes.length) {
        projects.set(document.id, {
          key: `@root:${document.id}`,
          label: humanizeSegment(document.title) || 'Root',
          size: 1,
        });
        continue;
      }
      let selected = prefixes.find((prefix) => {
        const label = humanizeSegment(prefix.split('/').pop());
        const count = counts.get(prefix) || 0;
        return count >= 2 && count <= maximumSize && !isGenericLabel(label);
      });
      if (!selected) {
        selected = [...prefixes].reverse().find((prefix) => {
          const label = humanizeSegment(prefix.split('/').pop());
          return (counts.get(prefix) || 0) >= 2 && !isGenericLabel(label);
        });
      }
      if (!selected && prefixes.length) selected = prefixes[0];
      const rawLabel = selected ? selected.split('/').pop() : 'Root';
      const projectLabel = humanizeSegment(rawLabel) || 'Root';
      projects.set(document.id, {
        key: selected || 'Root',
        label: projectLabel,
        size: selected ? counts.get(selected) || 1 : 1,
      });
    }
    return projects;
  }

  function buildDocumentFeatures(documents, projects, options = {}) {
    const priorityKeywords = parsePriorityKeywords(options.priorityKeywords);
    const features = new Map();
    for (const document of documents.values()) {
      const vector = new Map();
      const labelTerms = new Map();
      const project = projects.get(document.id);
      addTextFeatures(vector, document.title, 3.6);
      addTextFeatures(labelTerms, document.title, 3.6);
      for (const alias of document.aliases) {
        addTextFeatures(vector, alias, 3.1);
        addTextFeatures(labelTerms, alias, 3.1);
      }
      for (const tag of document.tags) {
        addTextFeatures(vector, tag, 4.8);
        addTextFeatures(labelTerms, tag, 4.8);
      }
      const pathSegments = document.path.split('/').slice(0, -1).map(humanizeSegment);
      pathSegments.forEach((segment, index) => {
        const weight = index === pathSegments.length - 1 ? 2.8 : 1.9;
        addTextFeatures(vector, segment, weight);
        addTextFeatures(labelTerms, segment, weight * 0.75);
      });
      for (const heading of document.headings) addTextFeatures(vector, heading, 1.15);

      const searchable = [
        document.path,
        document.title,
        ...document.aliases,
        ...document.tags,
        ...document.headings,
      ].join(' ').normalize('NFKC').toLocaleLowerCase();
      const priorityMatches = priorityKeywords.filter((keyword) => searchable.includes(keyword));
      for (const keyword of priorityMatches) {
        vector.set(`@priority:${keyword}`, 4);
        labelTerms.set(keyword, 8);
      }
      if (project && !isGenericLabel(project.label)) labelTerms.set(project.label, 5);
      features.set(document.id, { vector, labelTerms, priorityMatches });
    }
    return { features, priorityKeywords };
  }

  function buildHybridGraph(linkGraph, documentInput = [], options = {}) {
    const documents = normalizeDocumentInput(documentInput, linkGraph);
    const projects = deriveProjectAssignments(documents, options);
    const { features, priorityKeywords } = buildDocumentFeatures(documents, projects, options);
    const linkWeight = clamp(numericOption(options, 'linkWeight', 0.65), 0, 10);
    const navigationPenalty = clamp(numericOption(options, 'navigationLinkPenalty', 0.08), 0, 1);
    const graph = cloneGraph(linkGraph, (source, target, weight) => {
      const sourceNavigation = isNavigationDocument(source, documents.get(source));
      const targetNavigation = isNavigationDocument(target, documents.get(target));
      return weight * linkWeight * (sourceNavigation || targetNavigation ? navigationPenalty : 1);
    });

    addProjectEdges(graph, projects, options);
    addSemanticEdges(graph, features, options);
    for (const [id, document] of documents.entries()) {
      const project = projects.get(id);
      const feature = features.get(id);
      document.projectKey = project && project.key;
      document.projectLabel = project && project.label;
      document.labelTerms = feature && feature.labelTerms;
      document.priorityMatches = feature && feature.priorityMatches;
      document.navigation = isNavigationDocument(id, document);
    }
    return { graph, documents, projects, features, priorityKeywords };
  }

  function addProjectEdges(graph, projects, options = {}) {
    const weight = clamp(numericOption(options, 'projectWeight', 5), 0, 10);
    const neighbors = clamp(Math.round(numericOption(options, 'projectNeighbors', 3)), 0, 12);
    if (weight <= 0 || neighbors <= 0) return;
    const groups = new Map();
    for (const [id, project] of projects.entries()) {
      if (!groups.has(project.key)) groups.set(project.key, []);
      groups.get(project.key).push(id);
    }
    for (const members of groups.values()) {
      members.sort((a, b) => a.localeCompare(b));
      if (members.length < 2) continue;
      const seen = new Set();
      const span = Math.min(neighbors, members.length - 1);
      for (let index = 0; index < members.length; index += 1) {
        for (let offset = 1; offset <= span; offset += 1) {
          const targetIndex = (index + offset) % members.length;
          const source = members[index];
          const target = members[targetIndex];
          const key = source < target ? `${source}\u0000${target}` : `${target}\u0000${source}`;
          if (seen.has(key)) continue;
          seen.add(key);
          addUndirectedEdge(graph, source, target, weight / Math.sqrt(offset));
        }
      }
    }
  }

  function addSemanticEdges(graph, features, options = {}) {
    const weight = clamp(numericOption(options, 'semanticWeight', 1.4), 0, 12);
    const neighborLimit = clamp(Math.round(numericOption(options, 'semanticNeighbors', 10)), 0, 30);
    const minimumSimilarity = clamp(numericOption(options, 'semanticThreshold', 0.08), 0, 1);
    if (weight <= 0 || neighborLimit <= 0) return;

    const documentCount = Math.max(1, features.size);
    const postings = new Map();
    for (const [id, feature] of features.entries()) {
      for (const [term, value] of feature.vector.entries()) {
        if (!postings.has(term)) postings.set(term, []);
        postings.get(term).push([id, value]);
      }
    }
    const norms = new Map([...features.keys()].map((id) => [id, 0]));
    const weightedPostings = new Map();
    for (const [term, entries] of postings.entries()) {
      if (entries.length < 2) continue;
      const idf = Math.log((documentCount + 1) / (entries.length + 1)) + 1;
      const weighted = entries.map(([id, value]) => [id, value * idf]);
      weightedPostings.set(term, weighted);
      for (const [id, value] of weighted) norms.set(id, (norms.get(id) || 0) + value * value);
    }
    for (const [id, value] of norms.entries()) norms.set(id, Math.sqrt(value) || 1);

    const dots = new Map();
    const maximumPosting = Math.max(24, Math.round(documentCount * 0.16));
    for (const [term, entries] of weightedPostings.entries()) {
      const isPriority = term.startsWith('@priority:');
      if (!isPriority && entries.length > maximumPosting) continue;
      entries.sort((a, b) => a[0].localeCompare(b[0]));
      const span = entries.length <= 48 ? entries.length - 1 : 8;
      for (let index = 0; index < entries.length; index += 1) {
        for (let offset = 1; offset <= span && offset < entries.length; offset += 1) {
          const targetIndex = (index + offset) % entries.length;
          if (index === targetIndex) continue;
          const [source, sourceValue] = entries[index];
          const [target, targetValue] = entries[targetIndex];
          const key = source < target ? `${source}\u0000${target}` : `${target}\u0000${source}`;
          dots.set(key, (dots.get(key) || 0) + sourceValue * targetValue);
        }
      }
    }

    const candidates = new Map([...features.keys()].map((id) => [id, []]));
    for (const [key, dot] of dots.entries()) {
      const [source, target] = key.split('\u0000');
      const similarity = dot / ((norms.get(source) || 1) * (norms.get(target) || 1));
      if (similarity < minimumSimilarity) continue;
      candidates.get(source).push({ source, target, similarity });
      candidates.get(target).push({ source, target, similarity });
    }
    const selected = new Map();
    for (const edges of candidates.values()) {
      edges.sort((a, b) => b.similarity - a.similarity || a.target.localeCompare(b.target));
      for (const edge of edges.slice(0, neighborLimit)) {
        const key = edge.source < edge.target
          ? `${edge.source}\u0000${edge.target}`
          : `${edge.target}\u0000${edge.source}`;
        selected.set(key, Math.max(selected.get(key) || 0, edge.similarity));
      }
    }
    for (const [key, similarity] of selected.entries()) {
      const [source, target] = key.split('\u0000');
      addUndirectedEdge(graph, source, target, similarity * weight);
    }
  }

  function weightedDegree(graph, node) {
    let total = 0;
    for (const weight of (graph.get(node) || new Map()).values()) total += weight;
    return total;
  }

  function totalEdgeWeight(graph) {
    let sum = 0;
    for (const node of graph.keys()) sum += weightedDegree(graph, node);
    return sum / 2;
  }

  function toIndexedGraph(graph) {
    const ids = [...graph.keys()].sort((a, b) => a.localeCompare(b));
    const index = new Map(ids.map((id, i) => [id, i]));
    const adjacency = ids.map(() => new Map());
    for (const [source, neighbors] of graph.entries()) {
      const i = index.get(source);
      if (i == null) continue;
      for (const [target, weight] of neighbors.entries()) {
        const j = index.get(target);
        if (j == null || weight <= 0) continue;
        adjacency[i].set(j, (adjacency[i].get(j) || 0) + weight);
      }
    }
    return { ids, adjacency };
  }

  function deterministicOrder(length, seed) {
    const values = Array.from({ length }, (_, i) => i);
    let state = (seed >>> 0) || 0x9e3779b9;
    const random = () => {
      state += 0x6d2b79f5;
      let t = state;
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
    for (let i = values.length - 1; i > 0; i -= 1) {
      const j = Math.floor(random() * (i + 1));
      [values[i], values[j]] = [values[j], values[i]];
    }
    return values;
  }

  function renumberPartition(partition) {
    const mapping = new Map();
    let next = 0;
    return partition.map((community) => {
      if (!mapping.has(community)) mapping.set(community, next++);
      return mapping.get(community);
    });
  }

  function oneLouvainLevel(adjacency, resolution, maxPasses, seed) {
    const count = adjacency.length;
    const communities = Array.from({ length: count }, (_, i) => i);
    const degrees = adjacency.map((neighbors) => {
      let sum = 0;
      for (const weight of neighbors.values()) sum += weight;
      return sum;
    });
    const totalDegree = degrees.reduce((sum, value) => sum + value, 0);
    const totals = degrees.slice();
    if (totalDegree <= 0) return { partition: communities, moved: false };

    let movedAtLeastOnce = false;
    for (let pass = 0; pass < maxPasses; pass += 1) {
      let movedThisPass = false;
      const order = deterministicOrder(count, seed + pass * 7919);
      for (const node of order) {
        const degree = degrees[node];
        if (degree <= 0) continue;
        const current = communities[node];
        const weightsByCommunity = new Map();
        for (const [neighbor, weight] of adjacency[node].entries()) {
          if (neighbor === node) continue;
          const community = communities[neighbor];
          weightsByCommunity.set(
            community,
            (weightsByCommunity.get(community) || 0) + weight
          );
        }

        totals[current] -= degree;
        let best = current;
        let bestGain = 0;
        const candidates = [...weightsByCommunity.keys()].sort((a, b) => a - b);
        if (!weightsByCommunity.has(current)) candidates.push(current);
        for (const community of candidates) {
          const connectedWeight = weightsByCommunity.get(community) || 0;
          const gain =
            connectedWeight - resolution * ((totals[community] || 0) * degree) / totalDegree;
          if (
            gain > bestGain + 1e-12 ||
            (Math.abs(gain - bestGain) <= 1e-12 && gain > 0 && community < best)
          ) {
            best = community;
            bestGain = gain;
          }
        }
        communities[node] = best;
        totals[best] = (totals[best] || 0) + degree;
        if (best !== current) {
          movedThisPass = true;
          movedAtLeastOnce = true;
        }
      }
      if (!movedThisPass) break;
    }
    return { partition: renumberPartition(communities), moved: movedAtLeastOnce };
  }

  function inducedGraph(adjacency, partition, communityCount) {
    const induced = Array.from({ length: communityCount }, () => new Map());
    for (let node = 0; node < adjacency.length; node += 1) {
      const sourceCommunity = partition[node];
      for (const [neighbor, weight] of adjacency[node].entries()) {
        const targetCommunity = partition[neighbor];
        induced[sourceCommunity].set(
          targetCommunity,
          (induced[sourceCommunity].get(targetCommunity) || 0) + weight
        );
      }
    }
    return induced;
  }

  function louvainPartition(graph, options = {}) {
    const resolution = clamp(Number(options.resolution) || 1, 0.1, 4);
    const maxPasses = clamp(Math.round(Number(options.maxPasses) || 20), 1, 100);
    const maxLevels = clamp(Math.round(Number(options.maxLevels) || 10), 1, 30);
    const { ids, adjacency: initialAdjacency } = toIndexedGraph(graph);
    if (!ids.length) return new Map();

    let adjacency = initialAdjacency;
    let members = ids.map((_, index) => [index]);
    for (let level = 0; level < maxLevels; level += 1) {
      const { partition } = oneLouvainLevel(
        adjacency,
        resolution,
        maxPasses,
        0x51f15e + level * 104729
      );
      const communityCount = Math.max(...partition) + 1;
      const nextMembers = Array.from({ length: communityCount }, () => []);
      for (let node = 0; node < partition.length; node += 1) {
        nextMembers[partition[node]].push(...members[node]);
      }
      members = nextMembers;
      if (communityCount === adjacency.length) break;
      adjacency = inducedGraph(adjacency, partition, communityCount);
      if (communityCount <= 1) break;
    }

    const result = new Map();
    members.forEach((originalIndexes, community) => {
      for (const index of originalIndexes) result.set(ids[index], community);
    });
    return result;
  }

  function consolidateCommunities(graph, rawPartition, options = {}) {
    const maxCommunities = clamp(
      Math.round(Number(options.maxCommunities) || DEFAULT_PALETTE.length),
      2,
      36
    );
    const minCommunitySize = clamp(
      Math.round(Number(options.minCommunitySize) || 2),
      1,
      1000
    );
    const documents = options.documents instanceof Map ? options.documents : new Map();
    const hasProjects = [...documents.values()].some(
      (document) => document.projectKey && !document.projectKey.startsWith('@root:')
    );
    if (hasProjects && options.projectFirst !== false) {
      return consolidateByProject(graph, documents, maxCommunities, minCommunitySize);
    }
    const groups = new Map();
    for (const node of graph.keys()) {
      if (weightedDegree(graph, node) <= 0) continue;
      const raw = rawPartition.get(node);
      if (raw == null) continue;
      if (!groups.has(raw)) groups.set(raw, []);
      groups.get(raw).push(node);
    }
    const ranked = [...groups.entries()]
      .map(([raw, nodes]) => ({
        raw,
        nodes,
        score: nodes.reduce((sum, node) => sum + weightedDegree(graph, node), 0),
        projectKey: dominantProjectKey(nodes, documents),
      }))
      .sort((a, b) => b.score - a.score || b.nodes.length - a.nodes.length || a.raw - b.raw);

    let eligible = ranked.filter((group) => group.nodes.length >= minCommunitySize);
    if (!eligible.length && ranked.length) eligible = [ranked[0]];
    const kept = [];
    const usedProjects = new Set();
    for (const group of eligible) {
      if (kept.length >= maxCommunities) break;
      if (group.projectKey && usedProjects.has(group.projectKey)) continue;
      kept.push(group);
      if (group.projectKey) usedProjects.add(group.projectKey);
    }
    const preferProjectDiversity = documents.size > 0 && options.preferProjectDiversity !== false;
    if (!preferProjectDiversity) {
      for (const group of eligible) {
        if (kept.length >= maxCommunities) break;
        if (!kept.includes(group)) kept.push(group);
      }
    }
    const keptRaw = new Map(kept.map((group, index) => [group.raw, index]));
    const keptProject = new Map();
    for (const group of kept) {
      if (group.projectKey && !keptProject.has(group.projectKey)) {
        keptProject.set(group.projectKey, keptRaw.get(group.raw));
      }
    }
    const assignments = new Map([...graph.keys()].map((node) => [node, -1]));
    for (const group of kept) {
      const finalCommunity = keptRaw.get(group.raw);
      for (const node of group.nodes) assignments.set(node, finalCommunity);
    }

    for (const group of ranked) {
      if (keptRaw.has(group.raw)) continue;
      const weights = new Map();
      for (const node of group.nodes) {
        for (const [neighbor, weight] of (graph.get(node) || new Map()).entries()) {
          const neighborRaw = rawPartition.get(neighbor);
          const finalCommunity = keptRaw.get(neighborRaw);
          if (finalCommunity == null) continue;
          weights.set(finalCommunity, (weights.get(finalCommunity) || 0) + weight);
        }
      }
      let best = group.projectKey && keptProject.has(group.projectKey)
        ? keptProject.get(group.projectKey)
        : -1;
      let bestWeight = 0;
      if (best < 0) {
        for (const [community, weight] of weights.entries()) {
          if (weight > bestWeight || (weight === bestWeight && community < best)) {
            best = community;
            bestWeight = weight;
          }
        }
      }
      for (const node of group.nodes) assignments.set(node, best);
    }
    return assignments;
  }

  function consolidateByProject(graph, documents, maxCommunities, minCommunitySize) {
    const projectGroups = new Map();
    for (const node of graph.keys()) {
      const document = documents.get(node) || {};
      const key = document.projectKey;
      if (!key || key.startsWith('@root:')) continue;
      if (!projectGroups.has(key)) {
        projectGroups.set(key, { key, label: document.projectLabel, nodes: [] });
      }
      projectGroups.get(key).nodes.push(node);
    }
    const ranked = [...projectGroups.values()]
      .filter((group) => group.nodes.length >= minCommunitySize)
      .map((group) => ({
        ...group,
        score: group.nodes.reduce((sum, node) => sum + weightedDegree(graph, node), 0),
      }))
      .sort((a, b) => b.nodes.length - a.nodes.length || b.score - a.score || a.key.localeCompare(b.key));
    if (!ranked.length) return new Map([...graph.keys()].map((node) => [node, -1]));

    const kept = ranked.slice(0, maxCommunities);
    const communityByProject = new Map(kept.map((group, index) => [group.key, index]));
    const assignments = new Map([...graph.keys()].map((node) => [node, -1]));
    for (const group of kept) {
      const community = communityByProject.get(group.key);
      for (const node of group.nodes) assignments.set(node, community);
    }

    for (const group of ranked.slice(maxCommunities)) {
      const weights = new Map();
      for (const node of group.nodes) {
        for (const [neighbor, weight] of (graph.get(node) || new Map()).entries()) {
          const community = assignments.get(neighbor);
          if (community == null || community < 0) continue;
          weights.set(community, (weights.get(community) || 0) + weight);
        }
      }
      const best = [...weights.entries()]
        .sort((a, b) => b[1] - a[1] || a[0] - b[0])[0]?.[0] ?? -1;
      for (const node of group.nodes) assignments.set(node, best);
    }

    for (const node of graph.keys()) {
      if ((assignments.get(node) ?? -1) >= 0) continue;
      const weights = new Map();
      for (const [neighbor, weight] of (graph.get(node) || new Map()).entries()) {
        const community = assignments.get(neighbor);
        if (community == null || community < 0) continue;
        weights.set(community, (weights.get(community) || 0) + weight);
      }
      const best = [...weights.entries()]
        .sort((a, b) => b[1] - a[1] || a[0] - b[0])[0]?.[0];
      if (best != null) assignments.set(node, best);
    }
    return assignments;
  }

  function dominantProjectKey(nodes, documents) {
    const counts = new Map();
    for (const node of nodes) {
      const key = documents.get(node) && documents.get(node).projectKey;
      if (!key) continue;
      counts.set(key, (counts.get(key) || 0) + 1);
    }
    return [...counts.entries()]
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0]?.[0];
  }

  function chooseHubs(graph, assignments, documents = new Map()) {
    const clusters = new Map();
    for (const [node, community] of assignments.entries()) {
      if (community < 0) continue;
      if (!clusters.has(community)) clusters.set(community, []);
      clusters.get(community).push(node);
    }
    const hubs = new Map();
    for (const [community, nodes] of clusters.entries()) {
      nodes.sort((a, b) => {
        const scoreDifference = representativeScore(graph, b, documents.get(b)) -
          representativeScore(graph, a, documents.get(a));
        return scoreDifference || a.localeCompare(b);
      });
      hubs.set(community, nodes[0]);
    }
    return hubs;
  }

  function representativeScore(graph, node, document = {}) {
    const degreeScore = Math.log1p(weightedDegree(graph, node));
    const titleTerms = tokenizeSemanticText(document.title || basenameWithoutExtension(node));
    const informationBonus = 1 + Math.min(0.45, titleTerms.length * 0.045);
    const navigationFactor = isNavigationDocument(node, document) ? 0.06 : 1;
    return degreeScore * informationBonus * navigationFactor;
  }

  function summarizeCommunity(nodes, documents, priorityKeywords = [], preferProjects = true) {
    const projectScores = new Map();
    const priorityScores = new Map();
    const termScores = new Map();
    for (const node of nodes) {
      const document = documents.get(node) || {};
      if (document.projectLabel && !isGenericLabel(document.projectLabel)) {
        projectScores.set(
          document.projectLabel,
          (projectScores.get(document.projectLabel) || 0) + 1
        );
      }
      for (const keyword of document.priorityMatches || []) {
        priorityScores.set(keyword, (priorityScores.get(keyword) || 0) + 1);
      }
      for (const [term, weight] of document.labelTerms || []) {
        if (isGenericLabel(term) || GENERIC_TERMS.has(normalizedTerm(term))) continue;
        termScores.set(term, (termScores.get(term) || 0) + weight);
      }
    }

    const rank = (scores) => [...scores.entries()]
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
    const priorityOrder = new Map(priorityKeywords.map((keyword, index) => [keyword, index]));
    const priorityRanked = rank(priorityScores).sort((a, b) => {
      const aOrder = priorityOrder.has(a[0]) ? priorityOrder.get(a[0]) : Number.MAX_SAFE_INTEGER;
      const bOrder = priorityOrder.has(b[0]) ? priorityOrder.get(b[0]) : Number.MAX_SAFE_INTEGER;
      return aOrder - bOrder || b[1] - a[1] || a[0].localeCompare(b[0]);
    });
    const projectRanked = rank(projectScores);
    const termRanked = rank(termScores);
    const strongPriorityMinimum = Math.max(2, Math.ceil(nodes.length * 0.55));
    const fallbackPriorityMinimum = Math.max(2, Math.ceil(nodes.length * 0.25));
    const projectMinimum = Math.max(2, Math.ceil(nodes.length * 0.15));
    let label;
    if (preferProjects && projectRanked[0] && projectRanked[0][1] >= projectMinimum) {
      label = projectRanked[0][0];
    } else if (priorityRanked[0] && priorityRanked[0][1] >= strongPriorityMinimum) {
      label = priorityRanked[0][0];
    } else if (priorityRanked[0] && priorityRanked[0][1] >= fallbackPriorityMinimum) {
      label = priorityRanked[0][0];
    } else if (projectRanked[0] && projectRanked[0][1] >= projectMinimum) {
      label = projectRanked[0][0];
    } else if (termRanked[0]) {
      label = termRanked[0][0];
    } else {
      label = 'Community';
    }
    const keywords = [...new Set([
      ...priorityRanked.map(([term]) => term),
      ...projectRanked.map(([term]) => term),
      ...termRanked.map(([term]) => term),
    ])]
      .filter((term) => term !== label && !isGenericLabel(term))
      .sort((a, b) => {
        const aPriority = priorityOrder.has(a) ? priorityOrder.get(a) : Number.MAX_SAFE_INTEGER;
        const bPriority = priorityOrder.has(b) ? priorityOrder.get(b) : Number.MAX_SAFE_INTEGER;
        return aPriority - bPriority;
      })
      .slice(0, 4);
    return { label: humanizeSegment(label) || 'Community', keywords };
  }

  function normalizeVector(vector) {
    const sum = vector.reduce((total, value) => total + value, 0);
    if (sum <= 0) return vector;
    return vector.map((value) => value / sum);
  }

  function numericOption(options, key, fallback) {
    const value = Number(options[key]);
    return Number.isFinite(value) ? value : fallback;
  }

  function propagateAffinities(graph, assignments, hubs, communityCount, options = {}) {
    const steps = clamp(Math.round(numericOption(options, 'propagationSteps', 4)), 0, 20);
    const strength = clamp(numericOption(options, 'propagationStrength', 0.52), 0, 0.95);
    const hubAnchor = clamp(numericOption(options, 'hubAnchor', 0.72), 0, 1);
    const oneHot = new Map();
    for (const node of graph.keys()) {
      const vector = Array(communityCount).fill(0);
      const community = assignments.get(node);
      if (community != null && community >= 0) vector[community] = 1;
      oneHot.set(node, vector);
    }
    let current = new Map([...oneHot.entries()].map(([node, vector]) => [node, vector.slice()]));

    for (let step = 0; step < steps; step += 1) {
      const next = new Map();
      for (const node of graph.keys()) {
        const base = oneHot.get(node);
        const vector = base.map((value) => value * (1 - strength));
        const degree = weightedDegree(graph, node);
        if (degree > 0) {
          for (const [neighbor, weight] of graph.get(node).entries()) {
            const neighborVector = current.get(neighbor);
            if (!neighborVector) continue;
            const ratio = (strength * weight) / degree;
            for (let i = 0; i < communityCount; i += 1) {
              vector[i] += neighborVector[i] * ratio;
            }
          }
        }
        next.set(node, normalizeVector(vector));
      }
      for (const [community, hub] of hubs.entries()) {
        const vector = next.get(hub) || Array(communityCount).fill(0);
        vector[community] += hubAnchor;
        next.set(hub, normalizeVector(vector));
      }
      current = next;
    }

    for (const [community, hub] of hubs.entries()) {
      const vector = Array(communityCount).fill(0);
      vector[community] = 1;
      current.set(hub, vector);
    }
    return current;
  }

  function hslToRgbInt(hue, saturation = 0.72, lightness = 0.6) {
    const h = ((hue % 360) + 360) % 360 / 360;
    const s = clamp(saturation, 0, 1);
    const l = clamp(lightness, 0, 1);
    if (s === 0) {
      const gray = Math.round(l * 255);
      return (gray << 16) | (gray << 8) | gray;
    }
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    const convert = (t0) => {
      let t = t0;
      if (t < 0) t += 1;
      if (t > 1) t -= 1;
      if (t < 1 / 6) return p + (q - p) * 6 * t;
      if (t < 1 / 2) return q;
      if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
      return p;
    };
    const r = Math.round(convert(h + 1 / 3) * 255);
    const g = Math.round(convert(h) * 255);
    const b = Math.round(convert(h - 1 / 3) * 255);
    return (r << 16) | (g << 8) | b;
  }

  function hexToRgbInt(hex) {
    const normalized = String(hex || '').replace('#', '').trim();
    if (!/^[0-9a-fA-F]{3}$|^[0-9a-fA-F]{6}$/.test(normalized)) return 0x8b92a1;
    const expanded =
      normalized.length === 3
        ? normalized.split('').map((character) => character + character).join('')
        : normalized;
    return parseInt(expanded, 16);
  }

  function rgbIntToHex(rgb) {
    return `#${(rgb >>> 0).toString(16).padStart(6, '0').slice(-6).toUpperCase()}`;
  }

  function srgbToLinear(channel) {
    const value = channel / 255;
    return value <= 0.04045 ? value / 12.92 : Math.pow((value + 0.055) / 1.055, 2.4);
  }

  function linearToSrgb(channel) {
    const value = channel <= 0.0031308
      ? channel * 12.92
      : 1.055 * Math.pow(channel, 1 / 2.4) - 0.055;
    return Math.round(clamp(value, 0, 1) * 255);
  }

  function blendRgbInts(colors, weights) {
    let total = 0;
    let red = 0;
    let green = 0;
    let blue = 0;
    for (let i = 0; i < colors.length; i += 1) {
      const weight = Math.max(0, Number(weights[i]) || 0);
      if (!weight) continue;
      const color = colors[i];
      red += srgbToLinear((color >> 16) & 0xff) * weight;
      green += srgbToLinear((color >> 8) & 0xff) * weight;
      blue += srgbToLinear(color & 0xff) * weight;
      total += weight;
    }
    if (!total) return 0x8b92a1;
    const r = linearToSrgb(red / total);
    const g = linearToSrgb(green / total);
    const b = linearToSrgb(blue / total);
    return (r << 16) | (g << 8) | b;
  }

  function mixRgb(a, b, amount) {
    return blendRgbInts([a, b], [1 - clamp(amount, 0, 1), clamp(amount, 0, 1)]);
  }

  function generatePalette(count, configuredPalette = DEFAULT_PALETTE) {
    const colors = configuredPalette.map(hexToRgbInt);
    const goldenAngle = 137.507764;
    while (colors.length < count) {
      colors.push(hslToRgbInt(210 + goldenAngle * colors.length, 0.76, 0.61));
    }
    return colors.slice(0, count);
  }

  function colorize(graph, assignments, hubs, affinities, options = {}) {
    const communityCount = hubs.size;
    const palette = generatePalette(communityCount, options.palette || DEFAULT_PALETTE);
    const neutral = hexToRgbInt(options.neutralColor || '#8B92A1');
    const peripheralFade = clamp(numericOption(options, 'peripheralFade', 0.18), 0, 0.85);
    const maxDegree = Math.max(1, ...[...graph.keys()].map((node) => weightedDegree(graph, node)));
    const hubSet = new Set(hubs.values());
    const colors = new Map();
    for (const node of graph.keys()) {
      const vector = affinities.get(node) || [];
      if (!vector.length || vector.every((value) => value <= 0)) {
        colors.set(node, neutral);
        continue;
      }
      const mixed = blendRgbInts(palette, vector);
      if (hubSet.has(node)) {
        colors.set(node, palette[assignments.get(node)] || mixed);
        continue;
      }
      const degreeRatio = Math.log1p(weightedDegree(graph, node)) / Math.log1p(maxDegree);
      const confidence = Math.max(...vector);
      const fade = peripheralFade * (1 - degreeRatio) * (0.65 + 0.35 * (1 - confidence));
      colors.set(node, mixRgb(mixed, neutral, fade));
    }
    return { colors, palette };
  }

  function analyzeGraph(graph, options = {}) {
    const documents = options.documents instanceof Map
      ? options.documents
      : normalizeDocumentInput(options.documents || [], graph);
    const analysisOptions = { ...options, documents };
    const rawPartition = louvainPartition(graph, analysisOptions);
    const assignments = consolidateCommunities(graph, rawPartition, analysisOptions);
    const hubs = chooseHubs(graph, assignments, documents);
    const affinities = propagateAffinities(
      graph,
      assignments,
      hubs,
      hubs.size,
      options
    );
    const { colors, palette } = colorize(graph, assignments, hubs, affinities, options);
    const usedLabels = new Map();
    const usedFinalLabels = new Set();
    const clusters = [...hubs.entries()].map(([id, hub]) => {
      const nodes = [...assignments.entries()]
        .filter(([, community]) => community === id)
        .map(([node]) => node);
      const summary = summarizeCommunity(
        nodes,
        documents,
        options.priorityKeywords || [],
        options.projectFirst !== false
      );
      const baseLabel = displayTopicLabel(summary.label);
      let label = baseLabel;
      const duplicateCount = usedLabels.get(baseLabel) || 0;
      if (duplicateCount > 0) {
        const qualifier = summary.keywords.find(
          (keyword) => displayTopicLabel(keyword) !== baseLabel
        );
        label = qualifier ? `${label} · ${displayTopicLabel(qualifier)}` : `${label} ${duplicateCount + 1}`;
      }
      if (usedFinalLabels.has(label)) label = `${label} ${duplicateCount + 1}`;
      usedLabels.set(baseLabel, duplicateCount + 1);
      usedFinalLabels.add(label);
      return {
        id,
        hub,
        label,
        keywords: summary.keywords.map(displayTopicLabel),
        color: palette[id],
        colorHex: rgbIntToHex(palette[id]),
        size: nodes.length,
        totalDegree: nodes.reduce((sum, node) => sum + weightedDegree(graph, node), 0),
      };
    });
    return {
      graph,
      assignments,
      affinities,
      colors,
      palette,
      clusters,
      neutralCount: [...assignments.values()].filter((community) => community < 0).length,
      nodeCount: graph.size,
      edgeWeight: totalEdgeWeight(graph),
    };
  }

  function displayTopicLabel(value) {
    const label = humanizeSegment(value) || 'Community';
    return /^[a-z][a-z0-9+#.]{1,4}$/i.test(label) ? label.toUpperCase() : label;
  }

  function colorDistance(a, b) {
    const ar = (a >> 16) & 0xff;
    const ag = (a >> 8) & 0xff;
    const ab = a & 0xff;
    const br = (b >> 16) & 0xff;
    const bg = (b >> 8) & 0xff;
    const bb = b & 0xff;
    return Math.sqrt((ar - br) ** 2 + (ag - bg) ** 2 + (ab - bb) ** 2);
  }

  function clamp(value, minimum, maximum) {
    return Math.min(maximum, Math.max(minimum, value));
  }

  module.exports = {
    DEFAULT_PALETTE,
    addUndirectedEdge,
    analyzeGraph,
    blendRgbInts,
    buildHybridGraph,
    buildWeightedGraph,
    chooseHubs,
    colorDistance,
    consolidateCommunities,
    createGraph,
    ensureNode,
    graphFromResolvedLinks,
    hexToRgbInt,
    humanizeSegment,
    isNavigationDocument,
    louvainPartition,
    mixRgb,
    propagateAffinities,
    parsePriorityKeywords,
    rgbIntToHex,
    totalEdgeWeight,
    weightedDegree,
  };

  return module.exports;
})();

'use strict';

const {
  Notice,
  Plugin,
  PluginSettingTab,
  Setting,
  debounce,
} = require('obsidian');
const core = GraphCommunitiesCore;

const DEFAULT_SETTINGS = {
  enabled: true,
  resolution: 1,
  maxCommunities: 12,
  minCommunitySize: 3,
  topicAware: true,
  priorityKeywords: 'AI, LLM, ASR, RAG, Agent',
  projectWeight: 5,
  semanticWeight: 1.4,
  linkWeight: 0.65,
  projectMaxSize: 1200,
  navigationLinkPenalty: 0.08,
  propagationSteps: 4,
  propagationStrength: 0.52,
  hubAnchor: 0.72,
  peripheralFade: 0.18,
  neutralColor: '#8B92A1',
  colorEdges: true,
  sameCommunityEdgeOpacity: 0.42,
  crossCommunityEdgeOpacity: 0.16,
  showLegend: true,
};

class GraphCommunitiesPlugin extends Plugin {
  async onload() {
    await this.loadSettings();
    this.analysis = null;
    this.focusedCommunity = null;
    this.focusedCommunityLabel = null;
    this.focusedNodeId = null;
    this.focusSource = null;
    this.statusBar = this.addStatusBarItem();
    this.statusBar.setText('Graph Communities: waiting');
    this.addSettingTab(new GraphCommunitiesSettingTab(this.app, this));

    this.scheduleRecompute = debounce(() => this.recompute(), 650, true);
    this.schedulePaint = debounce(() => this.paintAll(), 120, true);

    this.registerEvent(this.app.metadataCache.on('resolved', this.scheduleRecompute));
    this.registerEvent(this.app.vault.on('create', this.scheduleRecompute));
    this.registerEvent(this.app.vault.on('delete', this.scheduleRecompute));
    this.registerEvent(this.app.vault.on('rename', this.scheduleRecompute));
    this.registerEvent(this.app.vault.on('modify', this.scheduleRecompute));
    this.registerEvent(this.app.workspace.on('layout-change', this.schedulePaint));
    this.registerEvent(this.app.workspace.on('file-open', (file) => this.focusFromFile(file)));
    this.registerEvent(this.app.workspace.on('active-leaf-change', () => {
      const file = this.app.workspace.getActiveFile && this.app.workspace.getActiveFile();
      if (file) this.focusFromFile(file);
      else this.schedulePaint();
    }));

    this.registerInterval(
      window.setInterval(() => {
        if (this.settings.enabled && this.analysis) this.paintAll(false);
      }, 900)
    );

    this.addCommand({
      id: 'recompute-graph-communities',
      name: 'Recompute graph communities',
      callback: () => {
        this.recompute();
        new Notice('Graph Communities: recomputing clusters');
      },
    });

    this.addCommand({
      id: 'clear-graph-community-focus',
      name: 'Clear focused graph community',
      callback: () => this.clearFocus(),
    });

    this.addCommand({
      id: 'toggle-graph-community-colors',
      name: 'Toggle community colors',
      callback: async () => {
        this.settings.enabled = !this.settings.enabled;
        await this.saveSettings(false);
        if (this.settings.enabled) {
          await this.recompute();
        } else {
          this.restoreAll();
        }
      },
    });

    this.app.workspace.onLayoutReady(() => this.recompute());
  }

  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (await this.loadData()) || {});
  }

  async saveSettings(recompute = true) {
    await this.saveData(this.settings);
    if (recompute) this.scheduleRecompute();
    else this.schedulePaint();
  }

  buildGraph() {
    const files = this.app.vault.getMarkdownFiles();
    const linkGraph = core.graphFromResolvedLinks(
      this.app.metadataCache.resolvedLinks || {},
      files.map((file) => file.path)
    );
    const documents = files.map((file) => {
      const cache = this.app.metadataCache.getFileCache
        ? this.app.metadataCache.getFileCache(file) || {}
        : {};
      const frontmatter = cache.frontmatter || {};
      const tags = [
        ...(cache.tags || []).map((tag) => tag.tag),
        ...toStringArray(frontmatter.tags),
        ...toStringArray(frontmatter.tag),
      ];
      return {
        id: file.path,
        path: file.path,
        title: frontmatter.title || displayName(file.path),
        aliases: [
          ...toStringArray(frontmatter.aliases),
          ...toStringArray(frontmatter.alias),
        ],
        tags,
        headings: (cache.headings || []).map((heading) => heading.heading),
      };
    });
    return core.buildHybridGraph(linkGraph, documents, {
      priorityKeywords: this.settings.priorityKeywords,
      linkWeight: this.settings.topicAware ? this.settings.linkWeight : 1,
      projectWeight: this.settings.topicAware ? this.settings.projectWeight : 0,
      semanticWeight: this.settings.topicAware ? this.settings.semanticWeight : 0,
      navigationLinkPenalty: this.settings.topicAware
        ? this.settings.navigationLinkPenalty
        : 1,
      projectMaxSize: this.settings.projectMaxSize,
    });
  }

  async recompute() {
    if (!this.settings.enabled) {
      this.restoreAll();
      return;
    }
    const model = this.buildGraph();
    this.analysis = core.analyzeGraph(model.graph, {
      resolution: this.settings.resolution,
      maxCommunities: this.settings.maxCommunities,
      minCommunitySize: this.settings.minCommunitySize,
      propagationSteps: this.settings.propagationSteps,
      propagationStrength: this.settings.propagationStrength,
      hubAnchor: this.settings.hubAnchor,
      peripheralFade: this.settings.peripheralFade,
      neutralColor: this.settings.neutralColor,
      documents: model.documents,
      priorityKeywords: model.priorityKeywords,
      projectFirst: this.settings.topicAware,
    });
    this.restoreFocusAfterRecompute();
    this.updateStatusBar();
    this.paintAll();
  }

  restoreFocusAfterRecompute() {
    if (!this.analysis) return;
    if (this.focusSource === 'node' && this.focusedNodeId) {
      const community = this.analysis.assignments.get(this.focusedNodeId);
      if (community != null && community >= 0) {
        this.focusedCommunity = community;
        this.focusedCommunityLabel = this.clusterLabel(community);
        return;
      }
    }
    if (this.focusSource === 'community' && this.focusedCommunityLabel) {
      const cluster = this.analysis.clusters.find(
        (candidate) => candidate.label === this.focusedCommunityLabel
      );
      if (cluster) {
        this.focusedCommunity = cluster.id;
        return;
      }
    }
    this.clearFocus(false);
  }

  clusterLabel(community) {
    const cluster = this.analysis && this.analysis.clusters.find(
      (candidate) => candidate.id === community
    );
    return cluster ? cluster.label : null;
  }

  focusFromFile(file) {
    if (!this.analysis || !file || !file.path) return;
    const community = this.analysis.assignments.get(file.path);
    if (community == null || community < 0) {
      if (this.focusSource === 'node') this.clearFocus();
      return;
    }
    this.focusedCommunity = community;
    this.focusedCommunityLabel = this.clusterLabel(community);
    this.focusedNodeId = file.path;
    this.focusSource = 'node';
    this.updateStatusBar();
    this.paintAll(true);
  }

  toggleCommunityFocus(cluster) {
    if (this.focusSource === 'community' && this.focusedCommunity === cluster.id) {
      this.clearFocus();
      return;
    }
    this.focusedCommunity = cluster.id;
    this.focusedCommunityLabel = cluster.label;
    this.focusedNodeId = null;
    this.focusSource = 'community';
    this.updateStatusBar();
    this.paintAll(true);
  }

  clearFocus(repaint = true) {
    this.focusedCommunity = null;
    this.focusedCommunityLabel = null;
    this.focusedNodeId = null;
    this.focusSource = null;
    this.updateStatusBar();
    if (repaint) this.paintAll(true);
  }

  updateStatusBar() {
    if (!this.statusBar || !this.analysis) return;
    if (this.focusedCommunity != null) {
      const cluster = this.analysis.clusters.find(
        (candidate) => candidate.id === this.focusedCommunity
      );
      if (cluster) {
        this.statusBar.setText(
          `Graph Communities: ${cluster.label} · ${cluster.size} notes focused`
        );
        return;
      }
    }
    this.statusBar.setText(
      `Graph Communities: ${this.analysis.clusters.length} clusters · ${this.analysis.nodeCount} notes`
    );
  }

  graphLeaves() {
    return [
      ...this.app.workspace.getLeavesOfType('graph'),
      ...this.app.workspace.getLeavesOfType('localgraph'),
    ];
  }

  paintAll(forceChanged = true) {
    if (!this.settings.enabled || !this.analysis) return;
    for (const leaf of this.graphLeaves()) this.paintLeaf(leaf, forceChanged);
  }

  paintLeaf(leaf, forceChanged = true) {
    const view = leaf && leaf.view;
    const renderer = view && view.renderer;
    if (!renderer || !Array.isArray(renderer.nodes)) return;
    let changed = false;

    for (const node of renderer.nodes) {
      const rgb = this.analysis.colors.get(node.id);
      if (rgb == null) continue;
      const community = this.analysis.assignments.get(node.id);
      const isFocusedCommunity =
        this.focusedCommunity != null && community === this.focusedCommunity;
      let displayRgb = rgb;
      let alpha = 1;
      if (this.focusedCommunity != null) {
        if (isFocusedCommunity) {
          displayRgb = core.mixRgb(rgb, 0xffffff, node.id === this.focusedNodeId ? 0.34 : 0.1);
        } else {
          const neutral = core.hexToRgbInt(this.settings.neutralColor);
          displayRgb = core.mixRgb(rgb, neutral, 0.72);
          alpha = 0.16;
        }
      }
      if (!node.color || node.color.rgb !== displayRgb || node.color.a !== alpha) {
        node.color = { a: alpha, rgb: displayRgb };
        changed = true;
      }
    }

    if (Array.isArray(renderer.links)) {
      const defaultLine = renderer.colors && renderer.colors.line;
      for (const link of renderer.links) {
        if (!this.settings.colorEdges) {
          if (!link.line) continue;
          const defaultTint = defaultLine && defaultLine.rgb;
          const defaultAlpha = defaultLine && defaultLine.a != null ? defaultLine.a : 1;
          if (defaultTint != null && link.line.tint !== defaultTint) {
            link.line.tint = defaultTint;
            changed = true;
          }
          if (link.line.alpha !== defaultAlpha) {
            link.line.alpha = defaultAlpha;
            changed = true;
          }
          continue;
        }
        const sourceId = nodeId(link.source);
        const targetId = nodeId(link.target);
        const sourceColor = this.analysis.colors.get(sourceId);
        const targetColor = this.analysis.colors.get(targetId);
        if (sourceColor == null || targetColor == null || !link.line) continue;
        const tint = core.blendRgbInts([sourceColor, targetColor], [1, 1]);
        const sourceCommunity = this.analysis.assignments.get(sourceId);
        const targetCommunity = this.analysis.assignments.get(targetId);
        const sameCommunity =
          sourceCommunity != null &&
          sourceCommunity >= 0 &&
          sourceCommunity === targetCommunity;
        let alpha = sameCommunity
          ? this.settings.sameCommunityEdgeOpacity
          : this.settings.crossCommunityEdgeOpacity;
        let displayTint = tint;
        if (this.focusedCommunity != null) {
          const sourceFocused = sourceCommunity === this.focusedCommunity;
          const targetFocused = targetCommunity === this.focusedCommunity;
          if (sourceFocused && targetFocused) {
            alpha = Math.max(alpha, 0.68);
            displayTint = core.mixRgb(tint, 0xffffff, 0.08);
          } else if (sourceFocused || targetFocused) {
            alpha = 0.18;
          } else {
            alpha = 0.025;
            displayTint = core.mixRgb(
              tint,
              core.hexToRgbInt(this.settings.neutralColor),
              0.75
            );
          }
        }
        if (link.line.tint !== displayTint) {
          link.line.tint = displayTint;
          changed = true;
        }
        if (link.line.alpha !== alpha) {
          link.line.alpha = alpha;
          changed = true;
        }
      }
    }

    const legend = view.containerEl && view.containerEl.querySelector('.graph-communities-legend');
    if (forceChanged || !legend) this.updateLegend(view);
    if ((changed || forceChanged) && typeof renderer.changed === 'function') {
      renderer.changed();
    }
  }

  updateLegend(view) {
    const container = view && view.containerEl;
    if (!container) return;
    let legend = container.querySelector('.graph-communities-legend');
    if (!this.settings.showLegend || !this.settings.enabled || !this.analysis) {
      if (legend) legend.remove();
      return;
    }
    if (!legend) {
      legend = document.createElement('div');
      legend.className = 'graph-communities-legend';
      container.appendChild(legend);
    }
    legend.replaceChildren();
    const title = document.createElement('div');
    title.className = 'graph-communities-legend-title';
    title.textContent = 'Topic communities';
    legend.appendChild(title);
    const hint = document.createElement('div');
    hint.className = 'graph-communities-legend-hint';
    hint.textContent = this.focusedNodeId
      ? `Selected: ${displayName(this.focusedNodeId)}`
      : 'Click a category to focus · click again to clear';
    legend.appendChild(hint);
    for (const cluster of this.analysis.clusters) {
      const row = document.createElement('div');
      const isActive = cluster.id === this.focusedCommunity;
      row.className = `graph-communities-legend-row${isActive ? ' is-active' : ''}`;
      row.setAttribute && row.setAttribute('role', 'button');
      row.setAttribute && row.setAttribute('aria-pressed', isActive ? 'true' : 'false');
      row.tabIndex = 0;
      const swatch = document.createElement('span');
      swatch.className = 'graph-communities-swatch';
      swatch.style.backgroundColor = cluster.colorHex;
      const label = document.createElement('span');
      label.className = 'graph-communities-label';
      label.textContent = `${cluster.label} (${cluster.size})`;
      label.title = [
        `Representative: ${displayName(cluster.hub)}`,
        cluster.keywords.length ? `Keywords: ${cluster.keywords.join(', ')}` : '',
      ].filter(Boolean).join(' · ');
      row.append(swatch, label);
      const activate = (event) => {
        if (event && event.stopPropagation) event.stopPropagation();
        this.toggleCommunityFocus(cluster);
      };
      if (typeof row.addEventListener === 'function') {
        row.addEventListener('click', activate);
        row.addEventListener('keydown', (event) => {
          if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            activate(event);
          }
        });
      }
      legend.appendChild(row);
    }
  }

  restoreAll() {
    for (const leaf of this.graphLeaves()) {
      const view = leaf && leaf.view;
      const renderer = view && view.renderer;
      if (!renderer || !Array.isArray(renderer.nodes)) continue;
      const fill = (renderer.colors && renderer.colors.fill) || { a: 1, rgb: 0x999999 };
      const line = (renderer.colors && renderer.colors.line) || { a: 1, rgb: 0x999999 };
      for (const node of renderer.nodes) node.color = { a: fill.a, rgb: fill.rgb };
      if (Array.isArray(renderer.links)) {
        for (const link of renderer.links) {
          if (!link.line) continue;
          link.line.tint = line.rgb;
          link.line.alpha = line.a == null ? 1 : line.a;
        }
      }
      const legend = view.containerEl && view.containerEl.querySelector('.graph-communities-legend');
      if (legend) legend.remove();
      if (typeof renderer.changed === 'function') renderer.changed();
    }
    if (this.statusBar) this.statusBar.setText('Graph Communities: off');
  }

  onunload() {
    this.restoreAll();
  }
}

function nodeId(value) {
  if (typeof value === 'string') return value;
  return value && value.id;
}

function displayName(path) {
  const value = String(path || 'Unknown');
  const basename = value.split('/').pop() || value;
  return basename.replace(/\.md$/i, '');
}

function toStringArray(value) {
  if (Array.isArray(value)) return value.flatMap(toStringArray).filter(Boolean);
  if (value == null) return [];
  return String(value).split(/[,，]/u).map((entry) => entry.trim()).filter(Boolean);
}

class GraphCommunitiesSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl('h2', { text: 'Graph Communities' });
    containerEl.createEl('p', {
      text: 'Automatically detect link communities. Major hubs receive distinct colors; nearby and boundary notes inherit or blend those colors.',
    });

    new Setting(containerEl)
      .setName('Enable community colors')
      .setDesc('Color global and local graph nodes without changing any notes.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
          this.plugin.settings.enabled = value;
          await this.plugin.saveSettings(false);
          if (value) await this.plugin.recompute();
          else this.plugin.restoreAll();
        })
      );

    new Setting(containerEl)
      .setName('Maximum communities')
      .setDesc('Limits the number of distinct major colors. Smaller communities merge into their strongest neighbor.')
      .addSlider((slider) =>
        slider
          .setLimits(2, 18, 1)
          .setValue(this.plugin.settings.maxCommunities)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.maxCommunities = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Minimum community size')
      .setDesc('Tiny groups are merged into connected major communities or shown in neutral gray.')
      .addSlider((slider) =>
        slider
          .setLimits(1, 20, 1)
          .setValue(this.plugin.settings.minCommunitySize)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.minCommunitySize = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Topic-aware clustering')
      .setDesc('Combine links with note titles, folders/projects, tags, aliases, and headings. Generic README/index notes are downweighted.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.topicAware).onChange(async (value) => {
          this.plugin.settings.topicAware = value;
          await this.plugin.saveSettings();
        })
      );

    new Setting(containerEl)
      .setName('Priority topic keywords')
      .setDesc('Comma-separated terms that should strongly influence grouping and community labels, for example: AI, ASR, Project Atlas.')
      .addTextArea((textArea) =>
        textArea
          .setPlaceholder('AI, LLM, ASR, Project Atlas')
          .setValue(this.plugin.settings.priorityKeywords)
          .onChange(async (value) => {
            this.plugin.settings.priorityKeywords = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Project/folder influence')
      .setDesc('How strongly notes from the same detected project directory stay together.')
      .addSlider((slider) =>
        slider
          .setLimits(0, 5, 0.1)
          .setValue(this.plugin.settings.projectWeight)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.projectWeight = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Keyword similarity influence')
      .setDesc('How strongly shared title, path, tag, alias, and heading terms affect grouping.')
      .addSlider((slider) =>
        slider
          .setLimits(0, 5, 0.1)
          .setValue(this.plugin.settings.semanticWeight)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.semanticWeight = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Clustering resolution')
      .setDesc('Lower values produce fewer, larger communities; higher values produce more, smaller communities.')
      .addSlider((slider) =>
        slider
          .setLimits(0.4, 2.2, 0.05)
          .setValue(this.plugin.settings.resolution)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.resolution = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Relationship blending')
      .setDesc('How strongly neighboring communities influence a node color. Higher values create smoother transitions.')
      .addSlider((slider) =>
        slider
          .setLimits(0, 0.85, 0.05)
          .setValue(this.plugin.settings.propagationStrength)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.propagationStrength = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Blending distance')
      .setDesc('Number of graph hops used to spread community colors.')
      .addSlider((slider) =>
        slider
          .setLimits(0, 10, 1)
          .setValue(this.plugin.settings.propagationSteps)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.propagationSteps = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Soften peripheral notes')
      .setDesc('Blend low-connectivity notes toward the neutral color so hubs remain visually distinct.')
      .addSlider((slider) =>
        slider
          .setLimits(0, 0.65, 0.05)
          .setValue(this.plugin.settings.peripheralFade)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.peripheralFade = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Neutral node color')
      .setDesc('Used for isolated notes and communities too small to classify.')
      .addColorPicker((picker) =>
        picker.setValue(this.plugin.settings.neutralColor).onChange(async (value) => {
          this.plugin.settings.neutralColor = value;
          await this.plugin.saveSettings();
        })
      );

    new Setting(containerEl)
      .setName('Color connections')
      .setDesc('Blend each edge from the colors of its endpoint nodes.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.colorEdges).onChange(async (value) => {
          this.plugin.settings.colorEdges = value;
          await this.plugin.saveSettings(false);
          this.plugin.paintAll();
        })
      );

    new Setting(containerEl)
      .setName('Show community legend')
      .setDesc('Display each community color, hub note, and node count inside the graph view.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.showLegend).onChange(async (value) => {
          this.plugin.settings.showLegend = value;
          await this.plugin.saveSettings(false);
          this.plugin.paintAll();
        })
      );
  }
}

module.exports = GraphCommunitiesPlugin;

