/*
 * Graph Communities for Obsidian
 * Generated from src/graph-core.js and src/plugin.js.
 * Do not edit this file directly; run: node scripts/build.mjs
 */
'use strict';

const GraphCommunitiesCore = (() => {
  const module = { exports: {} };
  const exports = module.exports;
  'use strict';
  
  const DEFAULT_PALETTE = [
    '#5AA9FF',
    '#FF7A7A',
    '#6FE39A',
    '#C58CFF',
    '#FFC857',
    '#46D7D0',
    '#FF86C8',
    '#A8D65E',
    '#FF9F43',
    '#738CFF',
    '#E3A6FF',
    '#6FD0FF',
  ];
  
  function createGraph(nodeIds = []) {
    const graph = new Map();
    for (const id of nodeIds) ensureNode(graph, id);
    return graph;
  }
  
  function ensureNode(graph, id) {
    const key = String(id);
    if (!graph.has(key)) graph.set(key, new Map());
    return graph.get(key);
  }
  
  function addUndirectedEdge(graph, source, target, weight = 1) {
    const a = String(source);
    const b = String(target);
    const w = Number(weight);
    ensureNode(graph, a);
    ensureNode(graph, b);
    if (a === b || !Number.isFinite(w) || w <= 0) return;
    graph.get(a).set(b, (graph.get(a).get(b) || 0) + w);
    graph.get(b).set(a, (graph.get(b).get(a) || 0) + w);
  }
  
  function buildWeightedGraph(edges = [], nodeIds = []) {
    const graph = createGraph(nodeIds);
    for (const edge of edges) {
      if (Array.isArray(edge)) {
        addUndirectedEdge(graph, edge[0], edge[1], edge[2] == null ? 1 : edge[2]);
      } else if (edge && edge.source != null && edge.target != null) {
        addUndirectedEdge(graph, edge.source, edge.target, edge.weight == null ? 1 : edge.weight);
      }
    }
    return graph;
  }
  
  function graphFromResolvedLinks(resolvedLinks = {}, nodeIds = []) {
    const graph = createGraph(nodeIds);
    for (const [source, targets] of Object.entries(resolvedLinks || {})) {
      ensureNode(graph, source);
      for (const [target, count] of Object.entries(targets || {})) {
        addUndirectedEdge(graph, source, target, Math.max(1, Number(count) || 1));
      }
    }
    return graph;
  }
  
  function weightedDegree(graph, node) {
    let total = 0;
    for (const weight of (graph.get(node) || new Map()).values()) total += weight;
    return total;
  }
  
  function totalEdgeWeight(graph) {
    let sum = 0;
    for (const node of graph.keys()) sum += weightedDegree(graph, node);
    return sum / 2;
  }
  
  function toIndexedGraph(graph) {
    const ids = [...graph.keys()].sort((a, b) => a.localeCompare(b));
    const index = new Map(ids.map((id, i) => [id, i]));
    const adjacency = ids.map(() => new Map());
    for (const [source, neighbors] of graph.entries()) {
      const i = index.get(source);
      if (i == null) continue;
      for (const [target, weight] of neighbors.entries()) {
        const j = index.get(target);
        if (j == null || weight <= 0) continue;
        adjacency[i].set(j, (adjacency[i].get(j) || 0) + weight);
      }
    }
    return { ids, adjacency };
  }
  
  function deterministicOrder(length, seed) {
    const values = Array.from({ length }, (_, i) => i);
    let state = (seed >>> 0) || 0x9e3779b9;
    const random = () => {
      state += 0x6d2b79f5;
      let t = state;
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
    for (let i = values.length - 1; i > 0; i -= 1) {
      const j = Math.floor(random() * (i + 1));
      [values[i], values[j]] = [values[j], values[i]];
    }
    return values;
  }
  
  function renumberPartition(partition) {
    const mapping = new Map();
    let next = 0;
    return partition.map((community) => {
      if (!mapping.has(community)) mapping.set(community, next++);
      return mapping.get(community);
    });
  }
  
  function oneLouvainLevel(adjacency, resolution, maxPasses, seed) {
    const count = adjacency.length;
    const communities = Array.from({ length: count }, (_, i) => i);
    const degrees = adjacency.map((neighbors) => {
      let sum = 0;
      for (const weight of neighbors.values()) sum += weight;
      return sum;
    });
    const totalDegree = degrees.reduce((sum, value) => sum + value, 0);
    const totals = degrees.slice();
    if (totalDegree <= 0) return { partition: communities, moved: false };
  
    let movedAtLeastOnce = false;
    for (let pass = 0; pass < maxPasses; pass += 1) {
      let movedThisPass = false;
      const order = deterministicOrder(count, seed + pass * 7919);
      for (const node of order) {
        const degree = degrees[node];
        if (degree <= 0) continue;
        const current = communities[node];
        const weightsByCommunity = new Map();
        for (const [neighbor, weight] of adjacency[node].entries()) {
          if (neighbor === node) continue;
          const community = communities[neighbor];
          weightsByCommunity.set(
            community,
            (weightsByCommunity.get(community) || 0) + weight
          );
        }
  
        totals[current] -= degree;
        let best = current;
        let bestGain = 0;
        const candidates = [...weightsByCommunity.keys()].sort((a, b) => a - b);
        if (!weightsByCommunity.has(current)) candidates.push(current);
        for (const community of candidates) {
          const connectedWeight = weightsByCommunity.get(community) || 0;
          const gain =
            connectedWeight - resolution * ((totals[community] || 0) * degree) / totalDegree;
          if (
            gain > bestGain + 1e-12 ||
            (Math.abs(gain - bestGain) <= 1e-12 && gain > 0 && community < best)
          ) {
            best = community;
            bestGain = gain;
          }
        }
        communities[node] = best;
        totals[best] = (totals[best] || 0) + degree;
        if (best !== current) {
          movedThisPass = true;
          movedAtLeastOnce = true;
        }
      }
      if (!movedThisPass) break;
    }
    return { partition: renumberPartition(communities), moved: movedAtLeastOnce };
  }
  
  function inducedGraph(adjacency, partition, communityCount) {
    const induced = Array.from({ length: communityCount }, () => new Map());
    for (let node = 0; node < adjacency.length; node += 1) {
      const sourceCommunity = partition[node];
      for (const [neighbor, weight] of adjacency[node].entries()) {
        const targetCommunity = partition[neighbor];
        induced[sourceCommunity].set(
          targetCommunity,
          (induced[sourceCommunity].get(targetCommunity) || 0) + weight
        );
      }
    }
    return induced;
  }
  
  function louvainPartition(graph, options = {}) {
    const resolution = clamp(Number(options.resolution) || 1, 0.1, 4);
    const maxPasses = clamp(Math.round(Number(options.maxPasses) || 20), 1, 100);
    const maxLevels = clamp(Math.round(Number(options.maxLevels) || 10), 1, 30);
    const { ids, adjacency: initialAdjacency } = toIndexedGraph(graph);
    if (!ids.length) return new Map();
  
    let adjacency = initialAdjacency;
    let members = ids.map((_, index) => [index]);
    for (let level = 0; level < maxLevels; level += 1) {
      const { partition } = oneLouvainLevel(
        adjacency,
        resolution,
        maxPasses,
        0x51f15e + level * 104729
      );
      const communityCount = Math.max(...partition) + 1;
      const nextMembers = Array.from({ length: communityCount }, () => []);
      for (let node = 0; node < partition.length; node += 1) {
        nextMembers[partition[node]].push(...members[node]);
      }
      members = nextMembers;
      if (communityCount === adjacency.length) break;
      adjacency = inducedGraph(adjacency, partition, communityCount);
      if (communityCount <= 1) break;
    }
  
    const result = new Map();
    members.forEach((originalIndexes, community) => {
      for (const index of originalIndexes) result.set(ids[index], community);
    });
    return result;
  }
  
  function consolidateCommunities(graph, rawPartition, options = {}) {
    const maxCommunities = clamp(
      Math.round(Number(options.maxCommunities) || DEFAULT_PALETTE.length),
      2,
      36
    );
    const minCommunitySize = clamp(
      Math.round(Number(options.minCommunitySize) || 2),
      1,
      1000
    );
    const groups = new Map();
    for (const node of graph.keys()) {
      if (weightedDegree(graph, node) <= 0) continue;
      const raw = rawPartition.get(node);
      if (raw == null) continue;
      if (!groups.has(raw)) groups.set(raw, []);
      groups.get(raw).push(node);
    }
    const ranked = [...groups.entries()]
      .map(([raw, nodes]) => ({
        raw,
        nodes,
        score: nodes.reduce((sum, node) => sum + weightedDegree(graph, node), 0),
      }))
      .sort((a, b) => b.score - a.score || b.nodes.length - a.nodes.length || a.raw - b.raw);
  
    let eligible = ranked.filter((group) => group.nodes.length >= minCommunitySize);
    if (!eligible.length && ranked.length) eligible = [ranked[0]];
    const kept = eligible.slice(0, maxCommunities);
    const keptRaw = new Map(kept.map((group, index) => [group.raw, index]));
    const assignments = new Map([...graph.keys()].map((node) => [node, -1]));
    for (const group of kept) {
      const finalCommunity = keptRaw.get(group.raw);
      for (const node of group.nodes) assignments.set(node, finalCommunity);
    }
  
    for (const group of ranked) {
      if (keptRaw.has(group.raw)) continue;
      const weights = new Map();
      for (const node of group.nodes) {
        for (const [neighbor, weight] of (graph.get(node) || new Map()).entries()) {
          const neighborRaw = rawPartition.get(neighbor);
          const finalCommunity = keptRaw.get(neighborRaw);
          if (finalCommunity == null) continue;
          weights.set(finalCommunity, (weights.get(finalCommunity) || 0) + weight);
        }
      }
      let best = -1;
      let bestWeight = 0;
      for (const [community, weight] of weights.entries()) {
        if (weight > bestWeight || (weight === bestWeight && community < best)) {
          best = community;
          bestWeight = weight;
        }
      }
      for (const node of group.nodes) assignments.set(node, best);
    }
    return assignments;
  }
  
  function chooseHubs(graph, assignments) {
    const clusters = new Map();
    for (const [node, community] of assignments.entries()) {
      if (community < 0) continue;
      if (!clusters.has(community)) clusters.set(community, []);
      clusters.get(community).push(node);
    }
    const hubs = new Map();
    for (const [community, nodes] of clusters.entries()) {
      nodes.sort((a, b) => {
        const degreeDifference = weightedDegree(graph, b) - weightedDegree(graph, a);
        return degreeDifference || a.localeCompare(b);
      });
      hubs.set(community, nodes[0]);
    }
    return hubs;
  }
  
  function normalizeVector(vector) {
    const sum = vector.reduce((total, value) => total + value, 0);
    if (sum <= 0) return vector;
    return vector.map((value) => value / sum);
  }
  
  function numericOption(options, key, fallback) {
    const value = Number(options[key]);
    return Number.isFinite(value) ? value : fallback;
  }
  
  function propagateAffinities(graph, assignments, hubs, communityCount, options = {}) {
    const steps = clamp(Math.round(numericOption(options, 'propagationSteps', 4)), 0, 20);
    const strength = clamp(numericOption(options, 'propagationStrength', 0.52), 0, 0.95);
    const hubAnchor = clamp(numericOption(options, 'hubAnchor', 0.72), 0, 1);
    const oneHot = new Map();
    for (const node of graph.keys()) {
      const vector = Array(communityCount).fill(0);
      const community = assignments.get(node);
      if (community != null && community >= 0) vector[community] = 1;
      oneHot.set(node, vector);
    }
    let current = new Map([...oneHot.entries()].map(([node, vector]) => [node, vector.slice()]));
  
    for (let step = 0; step < steps; step += 1) {
      const next = new Map();
      for (const node of graph.keys()) {
        const base = oneHot.get(node);
        const vector = base.map((value) => value * (1 - strength));
        const degree = weightedDegree(graph, node);
        if (degree > 0) {
          for (const [neighbor, weight] of graph.get(node).entries()) {
            const neighborVector = current.get(neighbor);
            if (!neighborVector) continue;
            const ratio = (strength * weight) / degree;
            for (let i = 0; i < communityCount; i += 1) {
              vector[i] += neighborVector[i] * ratio;
            }
          }
        }
        next.set(node, normalizeVector(vector));
      }
      for (const [community, hub] of hubs.entries()) {
        const vector = next.get(hub) || Array(communityCount).fill(0);
        vector[community] += hubAnchor;
        next.set(hub, normalizeVector(vector));
      }
      current = next;
    }
  
    for (const [community, hub] of hubs.entries()) {
      const vector = Array(communityCount).fill(0);
      vector[community] = 1;
      current.set(hub, vector);
    }
    return current;
  }
  
  function hslToRgbInt(hue, saturation = 0.72, lightness = 0.6) {
    const h = ((hue % 360) + 360) % 360 / 360;
    const s = clamp(saturation, 0, 1);
    const l = clamp(lightness, 0, 1);
    if (s === 0) {
      const gray = Math.round(l * 255);
      return (gray << 16) | (gray << 8) | gray;
    }
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    const convert = (t0) => {
      let t = t0;
      if (t < 0) t += 1;
      if (t > 1) t -= 1;
      if (t < 1 / 6) return p + (q - p) * 6 * t;
      if (t < 1 / 2) return q;
      if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
      return p;
    };
    const r = Math.round(convert(h + 1 / 3) * 255);
    const g = Math.round(convert(h) * 255);
    const b = Math.round(convert(h - 1 / 3) * 255);
    return (r << 16) | (g << 8) | b;
  }
  
  function hexToRgbInt(hex) {
    const normalized = String(hex || '').replace('#', '').trim();
    if (!/^[0-9a-fA-F]{3}$|^[0-9a-fA-F]{6}$/.test(normalized)) return 0x8b92a1;
    const expanded =
      normalized.length === 3
        ? normalized.split('').map((character) => character + character).join('')
        : normalized;
    return parseInt(expanded, 16);
  }
  
  function rgbIntToHex(rgb) {
    return `#${(rgb >>> 0).toString(16).padStart(6, '0').slice(-6).toUpperCase()}`;
  }
  
  function srgbToLinear(channel) {
    const value = channel / 255;
    return value <= 0.04045 ? value / 12.92 : Math.pow((value + 0.055) / 1.055, 2.4);
  }
  
  function linearToSrgb(channel) {
    const value = channel <= 0.0031308
      ? channel * 12.92
      : 1.055 * Math.pow(channel, 1 / 2.4) - 0.055;
    return Math.round(clamp(value, 0, 1) * 255);
  }
  
  function blendRgbInts(colors, weights) {
    let total = 0;
    let red = 0;
    let green = 0;
    let blue = 0;
    for (let i = 0; i < colors.length; i += 1) {
      const weight = Math.max(0, Number(weights[i]) || 0);
      if (!weight) continue;
      const color = colors[i];
      red += srgbToLinear((color >> 16) & 0xff) * weight;
      green += srgbToLinear((color >> 8) & 0xff) * weight;
      blue += srgbToLinear(color & 0xff) * weight;
      total += weight;
    }
    if (!total) return 0x8b92a1;
    const r = linearToSrgb(red / total);
    const g = linearToSrgb(green / total);
    const b = linearToSrgb(blue / total);
    return (r << 16) | (g << 8) | b;
  }
  
  function mixRgb(a, b, amount) {
    return blendRgbInts([a, b], [1 - clamp(amount, 0, 1), clamp(amount, 0, 1)]);
  }
  
  function generatePalette(count, configuredPalette = DEFAULT_PALETTE) {
    const colors = configuredPalette.map(hexToRgbInt);
    const goldenAngle = 137.507764;
    while (colors.length < count) {
      colors.push(hslToRgbInt(210 + goldenAngle * colors.length, 0.76, 0.61));
    }
    return colors.slice(0, count);
  }
  
  function colorize(graph, assignments, hubs, affinities, options = {}) {
    const communityCount = hubs.size;
    const palette = generatePalette(communityCount, options.palette || DEFAULT_PALETTE);
    const neutral = hexToRgbInt(options.neutralColor || '#8B92A1');
    const peripheralFade = clamp(numericOption(options, 'peripheralFade', 0.18), 0, 0.85);
    const maxDegree = Math.max(1, ...[...graph.keys()].map((node) => weightedDegree(graph, node)));
    const hubSet = new Set(hubs.values());
    const colors = new Map();
    for (const node of graph.keys()) {
      const vector = affinities.get(node) || [];
      if (!vector.length || vector.every((value) => value <= 0)) {
        colors.set(node, neutral);
        continue;
      }
      const mixed = blendRgbInts(palette, vector);
      if (hubSet.has(node)) {
        colors.set(node, palette[assignments.get(node)] || mixed);
        continue;
      }
      const degreeRatio = Math.log1p(weightedDegree(graph, node)) / Math.log1p(maxDegree);
      const confidence = Math.max(...vector);
      const fade = peripheralFade * (1 - degreeRatio) * (0.65 + 0.35 * (1 - confidence));
      colors.set(node, mixRgb(mixed, neutral, fade));
    }
    return { colors, palette };
  }
  
  function analyzeGraph(graph, options = {}) {
    const rawPartition = louvainPartition(graph, options);
    const assignments = consolidateCommunities(graph, rawPartition, options);
    const hubs = chooseHubs(graph, assignments);
    const affinities = propagateAffinities(
      graph,
      assignments,
      hubs,
      hubs.size,
      options
    );
    const { colors, palette } = colorize(graph, assignments, hubs, affinities, options);
    const clusters = [...hubs.entries()].map(([id, hub]) => {
      const nodes = [...assignments.entries()]
        .filter(([, community]) => community === id)
        .map(([node]) => node);
      return {
        id,
        hub,
        color: palette[id],
        colorHex: rgbIntToHex(palette[id]),
        size: nodes.length,
        totalDegree: nodes.reduce((sum, node) => sum + weightedDegree(graph, node), 0),
      };
    });
    return {
      graph,
      assignments,
      affinities,
      colors,
      palette,
      clusters,
      neutralCount: [...assignments.values()].filter((community) => community < 0).length,
      nodeCount: graph.size,
      edgeWeight: totalEdgeWeight(graph),
    };
  }
  
  function colorDistance(a, b) {
    const ar = (a >> 16) & 0xff;
    const ag = (a >> 8) & 0xff;
    const ab = a & 0xff;
    const br = (b >> 16) & 0xff;
    const bg = (b >> 8) & 0xff;
    const bb = b & 0xff;
    return Math.sqrt((ar - br) ** 2 + (ag - bg) ** 2 + (ab - bb) ** 2);
  }
  
  function clamp(value, minimum, maximum) {
    return Math.min(maximum, Math.max(minimum, value));
  }
  
  module.exports = {
    DEFAULT_PALETTE,
    addUndirectedEdge,
    analyzeGraph,
    blendRgbInts,
    buildWeightedGraph,
    chooseHubs,
    colorDistance,
    consolidateCommunities,
    createGraph,
    ensureNode,
    graphFromResolvedLinks,
    hexToRgbInt,
    louvainPartition,
    mixRgb,
    propagateAffinities,
    rgbIntToHex,
    totalEdgeWeight,
    weightedDegree,
  };
  
  return module.exports;
})();

'use strict';

const {
  Notice,
  Plugin,
  PluginSettingTab,
  Setting,
  debounce,
} = require('obsidian');
const core = GraphCommunitiesCore;

const DEFAULT_SETTINGS = {
  enabled: true,
  resolution: 1,
  maxCommunities: 9,
  minCommunitySize: 3,
  propagationSteps: 4,
  propagationStrength: 0.52,
  hubAnchor: 0.72,
  peripheralFade: 0.18,
  neutralColor: '#8B92A1',
  colorEdges: true,
  sameCommunityEdgeOpacity: 0.42,
  crossCommunityEdgeOpacity: 0.16,
  showLegend: true,
};

class GraphCommunitiesPlugin extends Plugin {
  async onload() {
    await this.loadSettings();
    this.analysis = null;
    this.statusBar = this.addStatusBarItem();
    this.statusBar.setText('Graph Communities: waiting');
    this.addSettingTab(new GraphCommunitiesSettingTab(this.app, this));

    this.scheduleRecompute = debounce(() => this.recompute(), 650, true);
    this.schedulePaint = debounce(() => this.paintAll(), 120, true);

    this.registerEvent(this.app.metadataCache.on('resolved', this.scheduleRecompute));
    this.registerEvent(this.app.vault.on('create', this.scheduleRecompute));
    this.registerEvent(this.app.vault.on('delete', this.scheduleRecompute));
    this.registerEvent(this.app.vault.on('rename', this.scheduleRecompute));
    this.registerEvent(this.app.vault.on('modify', this.scheduleRecompute));
    this.registerEvent(this.app.workspace.on('layout-change', this.schedulePaint));
    this.registerEvent(this.app.workspace.on('active-leaf-change', this.schedulePaint));

    this.registerInterval(
      window.setInterval(() => {
        if (this.settings.enabled && this.analysis) this.paintAll(false);
      }, 900)
    );

    this.addCommand({
      id: 'recompute-graph-communities',
      name: 'Recompute graph communities',
      callback: () => {
        this.recompute();
        new Notice('Graph Communities: recomputing clusters');
      },
    });

    this.addCommand({
      id: 'toggle-graph-community-colors',
      name: 'Toggle community colors',
      callback: async () => {
        this.settings.enabled = !this.settings.enabled;
        await this.saveSettings(false);
        if (this.settings.enabled) {
          await this.recompute();
        } else {
          this.restoreAll();
        }
      },
    });

    this.app.workspace.onLayoutReady(() => this.recompute());
  }

  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (await this.loadData()) || {});
  }

  async saveSettings(recompute = true) {
    await this.saveData(this.settings);
    if (recompute) this.scheduleRecompute();
    else this.schedulePaint();
  }

  buildGraph() {
    const files = this.app.vault.getMarkdownFiles();
    const graph = core.graphFromResolvedLinks(
      this.app.metadataCache.resolvedLinks || {},
      files.map((file) => file.path)
    );
    return graph;
  }

  async recompute() {
    if (!this.settings.enabled) {
      this.restoreAll();
      return;
    }
    const graph = this.buildGraph();
    this.analysis = core.analyzeGraph(graph, {
      resolution: this.settings.resolution,
      maxCommunities: this.settings.maxCommunities,
      minCommunitySize: this.settings.minCommunitySize,
      propagationSteps: this.settings.propagationSteps,
      propagationStrength: this.settings.propagationStrength,
      hubAnchor: this.settings.hubAnchor,
      peripheralFade: this.settings.peripheralFade,
      neutralColor: this.settings.neutralColor,
    });
    this.statusBar.setText(
      `Graph Communities: ${this.analysis.clusters.length} clusters · ${this.analysis.nodeCount} notes`
    );
    this.paintAll();
  }

  graphLeaves() {
    return [
      ...this.app.workspace.getLeavesOfType('graph'),
      ...this.app.workspace.getLeavesOfType('localgraph'),
    ];
  }

  paintAll(forceChanged = true) {
    if (!this.settings.enabled || !this.analysis) return;
    for (const leaf of this.graphLeaves()) this.paintLeaf(leaf, forceChanged);
  }

  paintLeaf(leaf, forceChanged = true) {
    const view = leaf && leaf.view;
    const renderer = view && view.renderer;
    if (!renderer || !Array.isArray(renderer.nodes)) return;
    let changed = false;

    for (const node of renderer.nodes) {
      const rgb = this.analysis.colors.get(node.id);
      if (rgb == null) continue;
      if (!node.color || node.color.rgb !== rgb || node.color.a !== 1) {
        node.color = { a: 1, rgb };
        changed = true;
      }
    }

    if (Array.isArray(renderer.links)) {
      const defaultLine = renderer.colors && renderer.colors.line;
      for (const link of renderer.links) {
        if (!this.settings.colorEdges) {
          if (!link.line) continue;
          const defaultTint = defaultLine && defaultLine.rgb;
          const defaultAlpha = defaultLine && defaultLine.a != null ? defaultLine.a : 1;
          if (defaultTint != null && link.line.tint !== defaultTint) {
            link.line.tint = defaultTint;
            changed = true;
          }
          if (link.line.alpha !== defaultAlpha) {
            link.line.alpha = defaultAlpha;
            changed = true;
          }
          continue;
        }
        const sourceId = nodeId(link.source);
        const targetId = nodeId(link.target);
        const sourceColor = this.analysis.colors.get(sourceId);
        const targetColor = this.analysis.colors.get(targetId);
        if (sourceColor == null || targetColor == null || !link.line) continue;
        const tint = core.blendRgbInts([sourceColor, targetColor], [1, 1]);
        const sourceCommunity = this.analysis.assignments.get(sourceId);
        const targetCommunity = this.analysis.assignments.get(targetId);
        const sameCommunity =
          sourceCommunity != null &&
          sourceCommunity >= 0 &&
          sourceCommunity === targetCommunity;
        const alpha = sameCommunity
          ? this.settings.sameCommunityEdgeOpacity
          : this.settings.crossCommunityEdgeOpacity;
        if (link.line.tint !== tint) {
          link.line.tint = tint;
          changed = true;
        }
        if (link.line.alpha !== alpha) {
          link.line.alpha = alpha;
          changed = true;
        }
      }
    }

    const legend = view.containerEl && view.containerEl.querySelector('.graph-communities-legend');
    if (forceChanged || !legend) this.updateLegend(view);
    if ((changed || forceChanged) && typeof renderer.changed === 'function') {
      renderer.changed();
    }
  }

  updateLegend(view) {
    const container = view && view.containerEl;
    if (!container) return;
    let legend = container.querySelector('.graph-communities-legend');
    if (!this.settings.showLegend || !this.settings.enabled || !this.analysis) {
      if (legend) legend.remove();
      return;
    }
    if (!legend) {
      legend = document.createElement('div');
      legend.className = 'graph-communities-legend';
      container.appendChild(legend);
    }
    legend.replaceChildren();
    const title = document.createElement('div');
    title.className = 'graph-communities-legend-title';
    title.textContent = 'Graph communities';
    legend.appendChild(title);
    for (const cluster of this.analysis.clusters) {
      const row = document.createElement('div');
      row.className = 'graph-communities-legend-row';
      const swatch = document.createElement('span');
      swatch.className = 'graph-communities-swatch';
      swatch.style.backgroundColor = cluster.colorHex;
      const label = document.createElement('span');
      label.className = 'graph-communities-label';
      label.textContent = `${displayName(cluster.hub)} (${cluster.size})`;
      row.append(swatch, label);
      legend.appendChild(row);
    }
  }

  restoreAll() {
    for (const leaf of this.graphLeaves()) {
      const view = leaf && leaf.view;
      const renderer = view && view.renderer;
      if (!renderer || !Array.isArray(renderer.nodes)) continue;
      const fill = (renderer.colors && renderer.colors.fill) || { a: 1, rgb: 0x999999 };
      const line = (renderer.colors && renderer.colors.line) || { a: 1, rgb: 0x999999 };
      for (const node of renderer.nodes) node.color = { a: fill.a, rgb: fill.rgb };
      if (Array.isArray(renderer.links)) {
        for (const link of renderer.links) {
          if (!link.line) continue;
          link.line.tint = line.rgb;
          link.line.alpha = line.a == null ? 1 : line.a;
        }
      }
      const legend = view.containerEl && view.containerEl.querySelector('.graph-communities-legend');
      if (legend) legend.remove();
      if (typeof renderer.changed === 'function') renderer.changed();
    }
    if (this.statusBar) this.statusBar.setText('Graph Communities: off');
  }

  onunload() {
    this.restoreAll();
  }
}

function nodeId(value) {
  if (typeof value === 'string') return value;
  return value && value.id;
}

function displayName(path) {
  const value = String(path || 'Unknown');
  const basename = value.split('/').pop() || value;
  return basename.replace(/\.md$/i, '');
}

class GraphCommunitiesSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl('h2', { text: 'Graph Communities' });
    containerEl.createEl('p', {
      text: 'Automatically detect link communities. Major hubs receive distinct colors; nearby and boundary notes inherit or blend those colors.',
    });

    new Setting(containerEl)
      .setName('Enable community colors')
      .setDesc('Color global and local graph nodes without changing any notes.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
          this.plugin.settings.enabled = value;
          await this.plugin.saveSettings(false);
          if (value) await this.plugin.recompute();
          else this.plugin.restoreAll();
        })
      );

    new Setting(containerEl)
      .setName('Maximum communities')
      .setDesc('Limits the number of distinct major colors. Smaller communities merge into their strongest neighbor.')
      .addSlider((slider) =>
        slider
          .setLimits(2, 18, 1)
          .setValue(this.plugin.settings.maxCommunities)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.maxCommunities = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Minimum community size')
      .setDesc('Tiny groups are merged into connected major communities or shown in neutral gray.')
      .addSlider((slider) =>
        slider
          .setLimits(1, 20, 1)
          .setValue(this.plugin.settings.minCommunitySize)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.minCommunitySize = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Clustering resolution')
      .setDesc('Lower values produce fewer, larger communities; higher values produce more, smaller communities.')
      .addSlider((slider) =>
        slider
          .setLimits(0.4, 2.2, 0.05)
          .setValue(this.plugin.settings.resolution)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.resolution = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Relationship blending')
      .setDesc('How strongly neighboring communities influence a node color. Higher values create smoother transitions.')
      .addSlider((slider) =>
        slider
          .setLimits(0, 0.85, 0.05)
          .setValue(this.plugin.settings.propagationStrength)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.propagationStrength = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Blending distance')
      .setDesc('Number of graph hops used to spread community colors.')
      .addSlider((slider) =>
        slider
          .setLimits(0, 10, 1)
          .setValue(this.plugin.settings.propagationSteps)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.propagationSteps = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Soften peripheral notes')
      .setDesc('Blend low-connectivity notes toward the neutral color so hubs remain visually distinct.')
      .addSlider((slider) =>
        slider
          .setLimits(0, 0.65, 0.05)
          .setValue(this.plugin.settings.peripheralFade)
          .setDynamicTooltip()
          .onChange(async (value) => {
            this.plugin.settings.peripheralFade = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName('Neutral node color')
      .setDesc('Used for isolated notes and communities too small to classify.')
      .addColorPicker((picker) =>
        picker.setValue(this.plugin.settings.neutralColor).onChange(async (value) => {
          this.plugin.settings.neutralColor = value;
          await this.plugin.saveSettings();
        })
      );

    new Setting(containerEl)
      .setName('Color connections')
      .setDesc('Blend each edge from the colors of its endpoint nodes.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.colorEdges).onChange(async (value) => {
          this.plugin.settings.colorEdges = value;
          await this.plugin.saveSettings(false);
          this.plugin.paintAll();
        })
      );

    new Setting(containerEl)
      .setName('Show community legend')
      .setDesc('Display each community color, hub note, and node count inside the graph view.')
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.showLegend).onChange(async (value) => {
          this.plugin.settings.showLegend = value;
          await this.plugin.saveSettings(false);
          this.plugin.paintAll();
        })
      );
  }
}

module.exports = GraphCommunitiesPlugin;

