import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const corePath = path.join(root, 'src', 'graph-core.js');
const pluginPath = path.join(root, 'src', 'plugin.js');
const outputPath = path.join(root, 'main.js');

const [coreSource, pluginSource] = await Promise.all([
  readFile(corePath, 'utf8'),
  readFile(pluginPath, 'utf8'),
]);

const bundledPlugin = pluginSource.replace(
  "const core = require('./graph-core');",
  'const core = GraphCommunitiesCore;'
);

if (bundledPlugin === pluginSource) {
  throw new Error('Could not locate the graph-core import in src/plugin.js');
}

const banner = `/*\n * Graph Communities for Obsidian\n * Generated from src/graph-core.js and src/plugin.js.\n * Do not edit this file directly; run: node scripts/build.mjs\n */\n`;

const output = `${banner}'use strict';\n\nconst GraphCommunitiesCore = (() => {\n  const module = { exports: {} };\n  const exports = module.exports;\n${indent(coreSource, 2)}\n  return module.exports;\n})();\n\n${bundledPlugin}\n`;

await writeFile(outputPath, output, 'utf8');
console.log(`Built ${path.relative(root, outputPath)}`);

function indent(text, spaces) {
  const prefix = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => line ? `${prefix}${line}` : '')
    .join('\n');
}
